
export const SET_DIARY_ID = 'SET_DIARY_ID'
export const SET_TIME = 'SET_TIME'
export const SET_SHOW_DIARIES = 'SET_SHOW_DIARIES'
export const SET_FLUSH_DIARIES = 'SET_FLUSH_DIARIES'
export const SET_FLUSH_PAGES = 'SET_FLUSH_PAGES'
export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const SET_IS_SHOW_CONTENT = 'SET_IS_SHOW_CONTENT'
export const SET_CURRENT_STRATERY = 'SET_CURRENT_STRATERY'
